// Catalogue partagé par l’éditeur, le formulaire public et la validation serveur.
export const QUESTION_IMAGE_OPTIONS = [
  ['site.webp', 'Ferme et serres'],
  ['small-farm.webp', 'Petite ferme et serres'],
  ['site-new.svg', 'Nouveau site — une serre'],
  ['site-existing.svg', 'Site existant — deux serres et contrôleur central'],
  ['shipping.webp', 'Livraison'],
  ['shipping_home.webp', 'Livraison à une autre adresse'],
  ['network.png', 'Réseau et contrôleur central'],
  ['network-ethernet.svg', 'Réseau — câble Ethernet'],
  ['network-wifi.svg', 'Réseau — Wi-Fi à 250 pi'],
  ['network-wifi-credentials.svg', 'Réseau — nom et mot de passe du Wi-Fi'],
  ['network-coax.svg', 'Réseau — antenne et câble coaxial'],
  ['network-mobile.svg', 'Réseau — contrôleur Internet mobile'],
  ['network_mobile.webp', 'Internet mobile'],
  ['dimensions-iso.svg', 'Dimensions de la serre'],
  ['length-200-or-less.svg', 'Serre de 200 pi ou moins'],
  ['length-over-200.svg', 'Serre de plus de 200 pi'],
  ['diameter.png', 'Diamètre des tuyaux'],
  ['diameter-2in.svg', 'Diamètre — 2 po, profil C'],
  ['diameter-1-5-16.svg', 'Diamètre — 1 5/16 po, tuyau rond'],
  ['diameter-other.svg', 'Diamètre — une autre mesure à préciser'],
  ['diameter-unknown.svg', 'Diamètre — mesure inconnue'],
  ['side-vents.png', 'Côtés ouvrants'],
  ['vent-height-6-or-less.svg', 'Côté ouvrant — 6 pi ou moins'],
  ['vent-height-over-6.svg', 'Côté ouvrant — plus de 6 pi'],
  ['vent-height-unknown.svg', 'Côté ouvrant — hauteur inconnue'],
  ['motors-existing.svg', 'Moteurs — déjà en place'],
  ['motors-needed.svg', 'Moteurs — à fournir'],
  ['motor-kingzo-24vdc.webp', 'Moteur Kingzo 24 V DC'],
  ['motor-lvm60-lvm100.webp', 'Moteur LVM60 / LVM100'],
  ['pipe-c.svg', 'Tuyau aluminium — profil C (illustration)'],
  ['pipe-o.svg', 'Tuyau acier — profil O (illustration)'],
  ['pipe-c.png', 'Tuyau aluminium — profil C'],
  ['pipe-o.png', 'Tuyau acier — profil O'],
  ['guide_pipes.webp', 'Tuyaux guides'],
  ['guide-pipes-present.webp', 'Tuyaux guides — déjà présents'],
  ['fans-two.svg', 'Deux ventilateurs de bout de serre'],
  ['roof-vent.svg', 'Toit ouvrant'],
  ['furnaces.webp', 'Fournaise'],
  ['furnace-wall-thermostat.webp', 'Fournaise — thermostat mural ordinaire'],
  ['furnace-dry-contact.svg', 'Fournaise — contact sec 24 V AC'],
  ['furnace_wire.webp', 'Filage de la fournaise'],
  ['thermostat.webp', 'Thermostat de secours'],
  ['irrigation.webp', 'Irrigation et valves'],
  ['valves-needed.svg', 'Valves 1 po à fournir par Orisha'],
  ['valves-existing.svg', 'Valves d’irrigation déjà en place'],
]

// Une entrée par illustration affichée, même si plusieurs champs partagent un bloc.
export const QUESTION_IMAGES = [
  ['order_type', 'order_type.image_new', 'site_new', 'Choix « nouveau site »'],
  ['order_type', 'order_type.image_existing', 'site_existing', 'Choix « site existant »'],
  ['farm', 'farm.title', 'farm'],
  ['shipping', 'shipping.prompt_new', 'shipping'],
  ['shipping', 'shipping.prompt_existing', 'shipping'],
  ['network', 'network.image_ethernet', 'network_ethernet', 'Choix « câble Ethernet »'],
  ['network', 'network.image_wifi_250', 'network_wifi', 'Choix « Wi-Fi à 250 pi »'],
  ['network', 'network.image_wifi_350_coax', 'network_coax', 'Choix « 350 pi avec coaxial »'],
  ['network', 'network.image_mobile_controller', 'network_mobile_choice', 'Choix « contrôleur Internet mobile »'],
  ['network', 'network.wifi', 'network_wifi_credentials', 'Nom et mot de passe du Wi-Fi'],
  ['greenhouses', 'greenhouses.count_label', 'count'],
  ['greenhouses', 'greenhouse.length_label', 'length'],
  ['greenhouses', 'greenhouse.image_length_up_to_200', 'length_up_to_200', 'Choix « 200 pi ou moins »'],
  ['greenhouses', 'greenhouse.image_length_over_200', 'length_over_200', 'Choix « plus de 200 pi »'],
  ['greenhouses', 'greenhouse.side_vent_height_label', 'vent_height'],
  ['greenhouses', 'greenhouse.image_vent_height_up_to_6', 'vent_height_up_to_6', 'Choix « 6 pi et moins »'],
  ['greenhouses', 'greenhouse.image_vent_height_over_6', 'vent_height_over_6', 'Choix « plus de 6 pi »'],
  ['greenhouses', 'greenhouse.image_vent_height_unknown', 'vent_height', 'Choix « hauteur inconnue »'],
  ['greenhouses', 'greenhouse.side_pipe_type_label', 'side_pipe'],
  ['greenhouses', 'greenhouse.image_diameter_standard', 'diameter_standard', 'Diamètre — choix « mesure standard »'],
  ['greenhouses', 'greenhouse.image_diameter_other', 'diameter_other', 'Diamètre — choix « autre mesure »'],
  ['greenhouses', 'greenhouse.image_diameter_unknown', 'diameter_unknown', 'Diamètre — choix « je ne sais pas »'],
  ['greenhouses', 'greenhouse.guide_pipes_label', 'guide_pipes'],
  ['greenhouses', 'greenhouse.image_motors_existing', 'motors_existing', 'Moteurs — choix « j’ai déjà mes moteurs »'],
  ['greenhouses', 'greenhouse.image_motors_needed', 'motors_needed', 'Moteurs — choix « j’ai besoin de moteurs »'],
  ['louvers', 'greenhouse.fans', 'fans_two', 'Ventilateurs de bout de serre'],
  ['chief', 'chief.has_furnaces_label', 'furnaces'],
  ['chief', 'chief.orisha_valves_label', 'valves'],
  ['furnace', 'furnace.dry_contact_label', 'furnace_dry_contact', 'Thermostat mural ordinaire'],
  ['furnace', 'furnace.brand_label', 'furnaces', 'Marque et modèle de fournaise'],
  ['furnace', 'furnace.wire_label', 'furnace_wire'],
  ['furnace', 'furnace.thermostat_label', 'thermostat'],
]

export const QUESTION_IMAGE_UPLOAD_PREFIX = '/erp/api/discovery-form-schema/images/'
export function isUploadedQuestionImage(value) {
  return typeof value === 'string' && /^\/erp\/api\/discovery-form-schema\/images\/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}\.webp$/.test(value)
}

export function normalizeQuestionImage(value) {
  return isUploadedQuestionImage(value) || value === 'none' || QUESTION_IMAGE_OPTIONS.some(([id]) => id === value) ? value : ''
}
