import { DownloadCloud,
  LayoutDashboard,
  Landmark,
  FolderOpen,
  Folder,
  TrendingUp,
  CheckSquare,
  LifeBuoy,
  MessageSquare,
  PhoneCall,
  Mail,
  ShoppingCart,
  Truck,
  RotateCcw,
  FileText,
  Tag,
  RefreshCw,
  Receipt,
  ReceiptText,
  CreditCard,
  BookOpen,
  ArrowLeftRight,
  ShoppingBag,
  Wrench,
  Package,
  Barcode,
  Users,
  Clock,
  Banknote,
  Wallet,
  Contact,
  Building2,
  Settings,
  Plug,
  Zap,
  Bot,
  LogIn,
  Ship,
  Megaphone,
  HardDrive,
  Instagram,
} from 'lucide-react'

// Order matters: most specific patterns first.
const ROUTES = [
  [/^\/login/, LogIn],
  [/^\/setup/, Settings],
  [/^\/dashboard/, LayoutDashboard],
  [/^\/public-files/, FolderOpen],
  [/^\/pipeline/, TrendingUp],
  [/^\/projects\/fields/, FolderOpen],
  [/^\/projects\//, Folder],
  [/^\/soumissions/, FileText],
  [/^\/tasks/, CheckSquare],
  [/^\/tickets/, LifeBuoy],
  [/^\/interactions/, MessageSquare],
  [/^\/qualification-call/, PhoneCall],
  [/^\/relance-qualification/, Mail],
  [/^\/orders/, ShoppingCart],
  [/^\/envois/, Truck],
  [/^\/retours/, RotateCcw],
  [/^\/factures/, FileText],
  [/^\/paiements/, Banknote],
  [/^\/items-vendus/, Tag],
  [/^\/finance/, Landmark],
  [/^\/comptes-prepayes/, Wallet],
  [/^\/inventaire-drive/, HardDrive],
  [/^\/dettes-lt/, Landmark],
  [/^\/budget-marketing/, Megaphone],
  [/^\/prospects-instagram/, Instagram],
  [/^\/douanes/, Ship],
  [/^\/collecte-factures/, DownloadCloud],
  [/^\/abonnements/, RefreshCw],
  [/^\/comptabilite/, Landmark],
  [/^\/fournisseurs/, Receipt],
  [/^\/depenses/, Receipt],
  [/^\/factures-fournisseurs/, Receipt],
  [/^\/sale-receipts/, ReceiptText],
  [/^\/stripe-payouts/, CreditCard],
  [/^\/journal-entries/, BookOpen],
  [/^\/comptabilite\/regles-serials/, BookOpen],
  [/^\/stock-movement/, ArrowLeftRight],
  [/^\/purchases/, ShoppingBag],
  [/^\/assemblages/, Wrench],
  [/^\/products/, Package],
  [/^\/serials/, Barcode],
  [/^\/employees/, Users],
  [/^\/feuille-de-temps/, Clock],
  [/^\/codes-activite/, Tag],
  [/^\/paies/, Banknote],
  [/^\/banque-heures/, Wallet],
  [/^\/contacts/, Contact],
  [/^\/companies/, Building2],
  [/^\/connectors/, Plug],
  [/^\/automations/, Zap],
  [/^\/agent/, Bot],
  [/^\/admin/, Settings],
]

export function iconForPath(pathname) {
  for (const [pattern, icon] of ROUTES) {
    if (pattern.test(pathname)) return icon
  }
  return LayoutDashboard
}
