// Métadonnées des colonnes par table — partagées entre les pages et l'admin.
// Les fonctions render() restent dans les composants de page.
// Ce fichier est la source de vérité pour : id, label, field, visibilité, tri, filtre, group.

export const TABLE_LABELS = {
  achats_fournisseurs:   'Achat fournisseur',
  tasks:          'Tâches',
  companies:      'Entreprises',
  contacts:       'Contacts',
  projects:       'Projets',
  products:       'Produits',
  orders:         'Commandes',
  interactions:   'Interactions',
  tickets:        'Billets',
  purchases:      'Achats',
  serial_numbers: 'Numéros de série',
  retours:        'Retours',
  factures:       'Factures',
  abonnements:    'Abonnements',
  assemblages:    'Assemblages',
  shipments:      'Envois',
  employees:      'Employés',
  paies:          'Paies',
  paie_items:     'Items de paie',
  stock_movements: "Mouvements d'inventaire",
  journal_entries: 'Écritures de journal',
  stripe_payouts: 'Stripe Payouts',
  automations:    'Automations',
  soumissions:    'Soumissions',
  catalog:        'Catalogue de produits',
  users:          'Utilisateurs',
  bom_items:      'BOM',
}

export const TABLE_ALL_LABEL = {
  achats_fournisseurs:   'Tous les achats fournisseurs',
  tasks:          'Toutes les tâches',
  companies:      'Toutes les entreprises',
  contacts:       'Tous les contacts',
  projects:       'Tous les projets',
  products:       'Tous les produits',
  orders:         'Toutes les commandes',
  interactions:   'Toutes les interactions',
  tickets:        'Tous les billets',
  purchases:      'Tous les achats',
  serial_numbers: 'Tous les numéros de série',
  retours:        'Tous les retours',
  factures:       'Toutes les factures',
  abonnements:    'Tous les abonnements',
  assemblages:    'Tous les assemblages',
  shipments:      'Tous les envois',
  employees:      'Tous les employés',
  paies:          'Toutes les paies',
  paie_items:     'Tous les items de paie',
  stock_movements: "Tous les mouvements",
  journal_entries: 'Toutes les écritures',
  stripe_payouts: 'Tous les payouts',
  automations:    'Toutes les automations',
  soumissions:    'Toutes les soumissions',
  catalog:        'Tout le catalogue',
  users:          'Tous les utilisateurs',
  bom_items:      'Tous les composants',
}

// Chaque entrée : { id, label, field, type?, options?, sortable?, filterable?, groupable?, defaultVisible? }
// type: 'text' (défaut) | 'number' | 'date' | 'boolean' | 'single_select'
export const TABLE_COLUMN_META = {
  tasks: [
    { id: 'title',         label: 'Titre',        field: 'title' },
    { id: 'type',          label: 'Type',         field: 'type',          type: 'single_select', options: ['Problème'] },
    { id: 'status',        label: 'Statut',       field: 'status',        type: 'single_select', options: ['À faire', 'En cours', 'Terminé', 'Annulé'] },
    { id: 'priority',      label: 'Priorité',     field: 'priority',      type: 'single_select', options: ['Basse', 'Normal', 'Haute', 'Urgente'] },
    { id: 'due_date',      label: 'Échéance',     field: 'due_date',      type: 'date' },
    { id: 'company_name',  label: 'Entreprise',   field: 'company_name',  defaultVisible: true },
    { id: 'contact_name',  label: 'Contact',      field: 'contact_name',  defaultVisible: true },
    { id: 'assigned_name', label: 'Responsable',  field: 'assigned_name', type: 'user', defaultVisible: false },
    { id: 'created_at',    label: 'Créée le',     field: 'created_at',    type: 'date', defaultVisible: false },
  ],

  companies: [
    { id: 'name',            label: 'Entreprise',   field: 'name' },
    { id: 'type',            label: 'Type',         field: 'type',            type: 'single_select', options: ['ASC', 'Serriculteur', 'Pépinière', 'Producteur fleurs', 'Centre jardin', 'Agriculture urbaine', 'Cannabis', 'Particulier', 'Distributeur', 'Partenaire', 'Compétiteur', 'Consultant', 'Autre'] },
    { id: 'phone',           label: 'Téléphone',    field: 'phone', type: 'phone' },
    { id: 'lifecycle_phase', label: 'Phase',        field: 'lifecycle_phase', type: 'single_select', options: ['Contact', 'Qualified', 'Problem aware', 'Solution aware', 'Lead', 'Quote Sent', 'Customer', 'Not a Client Anymore'] },
    { id: 'contacts_count',  label: 'Contacts',     field: 'contacts_count',  type: 'number', groupable: false, sortable: false },
  ],

  contacts: [
    { id: 'full_name',    label: 'Nom',         field: 'first_name' },
    { id: 'company_name', label: 'Entreprise',  field: 'company_name' },
    { id: 'email',        label: 'Courriel',    field: 'email' },
    { id: 'phone',        label: 'Téléphone',   field: 'phone',  type: 'phone' },
    { id: 'mobile',       label: 'Cellulaire',  field: 'mobile', type: 'phone', defaultVisible: false },
    { id: 'language',     label: 'Langue',      field: 'language',  type: 'single_select', options: ['French', 'English'] },
  ],

  projects: [
    { id: 'name',           label: 'Projet',            field: 'name' },
    { id: 'company_name',   label: 'Entreprise',        field: 'company_name' },
    { id: 'type',           label: 'Type',              field: 'type',        type: 'single_select', options: ['Nouveau client', 'Expansion', 'Ajouts mineurs', 'Pièces de rechange'] },
    { id: 'status',         label: 'Statut',            field: 'status',      type: 'single_select', options: ['Ouvert', 'Gagné', 'Perdu'] },
    { id: 'probability',    label: 'Probabilité',       field: 'probability', type: 'number', defaultVisible: false },
    { id: 'value_cad',      label: 'Valeur (CAD)',      field: 'value_cad',   type: 'number' },
    { id: 'monthly_cad',    label: 'Mensuel (CAD)',     field: 'monthly_cad', type: 'number', defaultVisible: false },
    { id: 'nb_greenhouses', label: 'Nb serres',         field: 'nb_greenhouses', type: 'number', defaultVisible: false },
    { id: 'orders',         label: 'Commandes',         field: 'orders',      groupable: false, sortable: false },
    { id: 'close_date',     label: 'Date de clôture',  field: 'close_date',  type: 'date' },
    { id: 'refusal_reason', label: 'Raison du refus',  field: 'refusal_reason', defaultVisible: false },
    { id: 'notes',          label: 'Notes',            field: 'notes',       defaultVisible: false },
    { id: 'created_at',     label: 'Créé le',          field: 'created_at',  type: 'date', defaultVisible: false },
    { id: 'updated_at',     label: 'Modifié le',       field: 'updated_at',  type: 'date', defaultVisible: false },
  ],

  products: [],

  orders: [
    { id: 'order_number',   label: '# Commande',       field: 'order_number' },
    { id: 'company_name',   label: 'Entreprise',        field: 'company_name' },
    { id: 'date_commande',  label: 'Date de commande',  field: 'date_commande', type: 'date' },
    { id: 'status',         label: 'Statut',            field: 'status',   type: 'single_select', options: ['Commande vide', "Gel d'envois", 'En attente', 'Items à fabriquer ou à acheter', 'Tous les items sont disponibles', 'Tout est dans la boite', 'Partiellement envoyé', 'Drop ship seulement', 'JWT-config', "Envoyé aujourd'hui", 'Envoyé', 'ERREUR SYSTÈME'] },
    { id: 'priority',       label: 'Priorité',          field: 'priority', type: 'single_select', options: ['low', 'normal', 'high', 'urgent'] },
    { id: 'items_count',    label: 'Items',             field: 'items_count', type: 'number', groupable: false, sortable: false },
    { id: 'assigned_name',  label: 'Assigné à',         field: 'assigned_name', type: 'user', defaultVisible: false },
  ],

  tickets: [
    { id: 'title',         label: 'Titre',      field: 'title' },
    { id: 'company_name',  label: 'Entreprise', field: 'company_name' },
    { id: 'status',        label: 'Statut',     field: 'status', type: 'single_select', options: ['open', 'in_progress', 'resolved', 'closed'] },
    { id: 'type',          label: 'Type',       field: 'type',   type: 'single_select', options: ['question', 'bug', 'feature', 'installation', 'maintenance', 'autre'] },
    { id: 'assigned_name', label: 'Assigné à',  field: 'assigned_name', type: 'user' },
    { id: 'duration_minutes', label: 'Durée (min)', field: 'duration_minutes', type: 'number', defaultVisible: false },
    { id: 'created_at', label: 'Créé le', field: 'created_at', type: 'date' },
  ],

  purchases: [
    { id: 'image',         label: 'Image',       field: 'product_image', sortable: false, filterable: false, groupable: false, defaultVisible: false },
    { id: 'product_name',  label: 'Produit',     field: 'product_name' },
    { id: 'supplier',      label: 'Fournisseur', field: 'supplier' },
    { id: 'status',        label: 'Statut',      field: 'status', type: 'single_select', options: ['pending', 'ordered', 'partial', 'received', 'cancelled'] },
    { id: 'qty_ordered',   label: 'Qté commandée', field: 'qty_ordered', type: 'number' },
    { id: 'qty_received',  label: 'Qté reçue',   field: 'qty_received', type: 'number' },
    { id: 'order_date',    label: "Date commande", field: 'order_date', type: 'date' },
    { id: 'expected_date', label: 'Date prévue',  field: 'expected_date', type: 'date', defaultVisible: false },
    { id: 'received_date', label: 'Date de réception complète', field: 'received_date', type: 'date', defaultVisible: false },
  ],

  serial_numbers: [
    { id: 'serial',        label: 'Numéro de série', field: 'serial' },
    { id: 'product_name',  label: 'Produit',         field: 'product_name' },
    { id: 'company_name',  label: 'Entreprise',      field: 'company_name' },
    { id: 'status',        label: 'Statut',          field: 'status', type: 'single_select', options: ['active', 'inactive', 'returned', 'lost'] },
    { id: 'manufacture_date', label: 'Date fab.',    field: 'manufacture_date', type: 'date', defaultVisible: false },
  ],

  interactions: [
    { id: 'type',         label: 'Type',        field: 'type',      type: 'single_select', options: ['call', 'email', 'meeting', 'note', 'sms'] },
    { id: 'direction',    label: 'Direction',   field: 'direction', type: 'single_select', options: ['inbound', 'outbound'] },
    { id: 'contact_name', label: 'Contact',     field: 'contact_name' },
    { id: 'company_name', label: 'Entreprise',  field: 'company_name' },
    { id: 'phone_number', label: 'Téléphone',   field: 'phone_number',     defaultVisible: false },
    { id: 'summary',      label: 'Résumé',      field: null,               sortable: false, filterable: false, groupable: false },
    { id: 'timestamp',    label: 'Date',        field: 'timestamp',        type: 'date' },
    { id: 'duration_seconds', label: 'Durée',   field: 'duration_seconds', type: 'number', defaultVisible: false },
    { id: 'user_name',    label: 'Utilisateur', field: 'user_name',        type: 'user', defaultVisible: false },
  ],

  retours: [
    { id: 'return_number',     label: 'N° de retour',         field: 'return_number' },
    { id: 'company_name',      label: 'Entreprise',           field: 'company_name' },
    { id: 'tracking_number',   label: 'Suivi',                field: 'tracking_number' },
    { id: 'processing_status', label: 'Statut de traitement', field: 'processing_status', type: 'single_select', options: ['Reçu', 'En attente', 'En traitement', 'Refusé'] },
    { id: 'created_at',        label: 'Date',                 field: 'created_at', type: 'date' },
  ],

  factures: [
    { id: 'document_number',       label: 'N° document',       field: 'document_number' },
    { id: 'invoice_id',            label: 'ID Stripe/source',  field: 'invoice_id',            defaultVisible: false },
    { id: 'company_name',          label: 'Entreprise',        field: 'company_name' },
    { id: 'project_name',          label: 'Projet',            field: 'project_name',          defaultVisible: false },
    { id: 'order_number',          label: 'Commande',          field: 'order_number',          defaultVisible: false },
    { id: 'status',                label: 'Statut',            field: 'status',                type: 'single_select', options: ['Payée', 'Partielle', 'En retard', 'Envoyée', 'Brouillon', 'Annulée'] },
    { id: 'document_date',         label: 'Date document',     field: 'document_date',         type: 'date' },
    { id: 'due_date',              label: 'Échéance',          field: 'due_date',              type: 'date', defaultVisible: false },
    { id: 'currency',              label: 'Devise',            field: 'currency',              type: 'single_select', options: ['CAD', 'USD', 'EUR'], defaultVisible: false },
    { id: 'amount_before_tax_cad', label: 'Avant taxes (CAD)', field: 'amount_before_tax_cad', type: 'number' },
    { id: 'total_amount',          label: 'Total',             field: 'total_amount',          type: 'number' },
    { id: 'balance_due',           label: 'Solde dû',          field: 'balance_due',           type: 'number' },
  ],

  abonnements: [
    { id: 'company_name', label: 'Entreprise', field: 'company_name' },
    { id: 'status',       label: 'Statut',     field: 'status', type: 'single_select', options: ['active', 'trialing', 'past_due', 'canceled', 'Actif', 'Inactif', 'Suspendu', 'Annulé', 'Expiré'] },
    { id: 'rachat',       label: 'Rachat',     field: 'rachat', defaultVisible: false },
    { id: 'amount_cad',   label: 'Montant (CAD)', field: 'amount_cad', type: 'number' },
    { id: 'start_date',   label: 'Début',      field: 'start_date', type: 'date' },
    { id: 'end_date',     label: 'Fin',        field: 'end_date',   type: 'date', defaultVisible: false },
    { id: 'stripe_url',   label: 'Stripe',     field: 'stripe_url', defaultVisible: false, sortable: false },
  ],

  assemblages: [
    { id: 'product_name', label: 'Produit',         field: 'product_name' },
    { id: 'qty_produced', label: 'Qté produite',    field: 'qty_produced', type: 'number' },
    { id: 'assembled_at', label: 'Date assemblage', field: 'assembled_at', type: 'date' },
  ],

  bom_items: [
    { id: 'component_image', label: 'Image',         field: 'component_image_url', sortable: false, filterable: false, groupable: false },
    { id: 'component_name',  label: 'Composant',     field: 'component_name' },
    { id: 'component_sku',   label: 'SKU composant', field: 'component_sku' },
    { id: 'qty_required',    label: 'Qté requise',   field: 'qty_required', type: 'number' },
    { id: 'ref_des',         label: 'Ref. des.',     field: 'ref_des' },
    { id: 'product_name',    label: 'Produit parent', field: 'product_name', defaultVisible: false },
    { id: 'product_sku',     label: 'SKU parent',     field: 'product_sku',  defaultVisible: false },
  ],

  employees: [
    { id: 'full_name',             label: 'Nom',                field: 'last_name' },
    { id: 'active',                label: 'Actif',              field: 'active', type: 'boolean' },
    { id: 'accounting_department', label: 'Département',        field: 'accounting_department', type: 'single_select', options: ['R&D', 'Opérations', 'Marketing'] },
    { id: 'matricule',             label: 'Matricule',          field: 'matricule', defaultVisible: false },
    { id: 'email_work',            label: 'Courriel travail',   field: 'email_work' },
    { id: 'email_personal',        label: 'Courriel perso',     field: 'email_personal', defaultVisible: false },
    { id: 'phone_work',            label: 'Téléphone travail',  field: 'phone_work', type: 'phone' },
    { id: 'phone_personal',        label: 'Téléphone perso',    field: 'phone_personal', type: 'phone', defaultVisible: false },
    { id: 'hire_date',             label: "Date d'embauche",    field: 'hire_date',  type: 'date' },
    { id: 'end_date',              label: "Date de fin",        field: 'end_date',   type: 'date', defaultVisible: false },
    { id: 'birth_date',            label: 'Date de naissance',  field: 'birth_date', type: 'date', defaultVisible: false },
    { id: 'gender',                label: 'Genre',              field: 'gender', type: 'single_select', options: ['Homme', 'Femme', 'Autre'], defaultVisible: false },
    { id: 'hours_per_week',        label: 'Heures/sem',         field: 'hours_per_week', type: 'number', defaultVisible: false },
    { id: 'last_raise_date',       label: 'Dernière augm.',     field: 'last_raise_date', type: 'date', defaultVisible: false },
    { id: 'is_salesperson',        label: 'Vendeur',            field: 'is_salesperson', type: 'boolean', defaultVisible: false },
    { id: 'is_consultant',         label: 'Consultant',         field: 'is_consultant',  type: 'boolean', defaultVisible: false },
    { id: 'group_insurance',       label: 'Assurance coll.',    field: 'group_insurance', type: 'boolean', defaultVisible: false },
    { id: 'office_key',            label: 'Clef bureau',        field: 'office_key', type: 'boolean', defaultVisible: false },
    { id: 'address',               label: 'Adresse',            field: 'address', defaultVisible: false },
    { id: 'address_verified',      label: 'Adresse validée',    field: 'address_verified', type: 'boolean', defaultVisible: false },
    { id: 'emergency_contact',     label: "Contact d'urgence",  field: 'emergency_contact', defaultVisible: false },
    { id: 'nethris_username',      label: 'Nethris username',   field: 'nethris_username', defaultVisible: false },
    { id: 'insurance_id',          label: 'ID Assurances',      field: 'insurance_id', defaultVisible: false },
    { id: 'banking_info',          label: 'Coord. bancaires',   field: 'banking_info', defaultVisible: false },
    { id: 'peer_reviews',          label: 'Éval. par pairs',    field: 'peer_reviews', defaultVisible: false },
    { id: 'issues',                label: 'Problèmes',          field: 'issues', defaultVisible: false },
  ],

  paies: [
    { id: 'number',                label: '#',                field: 'number', type: 'number' },
    { id: 'period_end',            label: 'Fin de période',   field: 'period_end', type: 'date' },
    { id: 'status',                label: 'Statut',           field: 'status', type: 'single_select', options: ['Non débuté','En cours','Complété','Envoyé'] },
    { id: 'items_count',           label: '# items',          field: 'items_count', type: 'number' },
    { id: 'total_regular_hours',   label: 'Heures rég.',      field: 'total_regular_hours', type: 'number' },
    { id: 'total_regular_amount',  label: '$ heures rég.',    field: 'total_regular_amount', type: 'number' },
    { id: 'total_with_charges_and_reimb', label: 'Total paie', field: 'total_with_charges_and_reimb', type: 'number' },
    { id: 'nb_holiday_days',       label: 'Congés fériés',    field: 'nb_holiday_days', type: 'number', defaultVisible: false },
    { id: 'timesheets_deadline',   label: 'Limite correction', field: 'timesheets_deadline', defaultVisible: false },
    { id: 'timesheets_sent',       label: 'FdT envoyées',     field: 'timesheets_sent', type: 'boolean', defaultVisible: false },
    { id: 'includes_hourly',       label: 'Inclut horaires',  field: 'includes_hourly', type: 'boolean', defaultVisible: false },
    { id: 'includes_mileage',      label: 'Inclut kilométrage', field: 'includes_mileage', type: 'boolean', defaultVisible: false },
    { id: 'includes_expense_reimb', label: 'Inclut remb. dép.', field: 'includes_expense_reimb', type: 'boolean', defaultVisible: false },
    { id: 'includes_paid_leave',   label: 'Inclut congés',    field: 'includes_paid_leave', type: 'boolean', defaultVisible: false },
    { id: 'includes_holiday_hours', label: 'Inclut fériés',   field: 'includes_holiday_hours', type: 'boolean', defaultVisible: false },
    { id: 'includes_sales_commissions', label: 'Inclut commissions', field: 'includes_sales_commissions', type: 'boolean', defaultVisible: false },
  ],

  paie_items: [
    { id: 'employee_name',  label: 'Employé',        field: 'last_name' },
    { id: 'period_end',     label: 'Fin de période', field: 'period_end', type: 'date' },
    { id: 'accounting_department', label: 'Département', field: 'accounting_department', type: 'single_select', options: ['R&D', 'Opérations', 'Marketing'] },
    { id: 'hourly_rate',    label: '$/h',            field: 'hourly_rate', type: 'number' },
    { id: 'regular_hours',  label: 'H. rég.',        field: 'regular_hours', type: 'number' },
    { id: 'holiday_hours',  label: 'H. fériées',     field: 'holiday_hours', type: 'number', defaultVisible: false },
    { id: 'vacation',       label: 'Vacances',       field: 'vacation', type: 'number', defaultVisible: false },
    { id: 'commission',     label: 'Commission',     field: 'commission', type: 'number' },
    { id: 'expense_reimb',  label: 'Remb. dépenses', field: 'expense_reimb', type: 'number', defaultVisible: false },
    { id: 'rsde_pct',       label: 'RSDE %',         field: 'rsde_pct', type: 'number', defaultVisible: false },
    { id: 'insurance_gains', label: 'Gains assur.',  field: 'insurance_gains', type: 'number', defaultVisible: false },
    { id: 'holiday_1_20',   label: 'Férié 1/20',     field: 'holiday_1_20', type: 'number', defaultVisible: false },
    { id: 'notes',          label: 'Notes',          field: 'notes', defaultVisible: false },
  ],

  achats_fournisseurs: [
    { id: 'type',             label: 'Type',          field: 'type',          type: 'single_select', options: ['bill','purchase'] },
    { id: 'date_achat',       label: 'Date',          field: 'date_achat',    type: 'date' },
    { id: 'vendor',           label: 'Fournisseur',   field: 'vendor' },
    { id: 'description',      label: 'Description',   field: 'description',   defaultVisible: false },
    { id: 'vendor_invoice_number', label: '# Fact. fourn.', field: 'vendor_invoice_number', defaultVisible: false },
    { id: 'bill_number',      label: '# Facture',     field: 'bill_number',   defaultVisible: false },
    { id: 'reference',        label: 'Référence',     field: 'reference',     defaultVisible: false },
    { id: 'category',         label: 'Catégorie',     field: 'category',      defaultVisible: false },
    { id: 'total_cad',        label: 'Total',         field: 'total_cad',     type: 'number' },
    { id: 'amount_paid_cad',  label: 'Payé',          field: 'amount_paid_cad', type: 'number', defaultVisible: false },
    { id: 'balance_due_cad',  label: 'Solde dû',      field: 'balance_due_cad', type: 'number' },
    { id: 'due_date',         label: 'Échéance',      field: 'due_date',      type: 'date', defaultVisible: false },
    { id: 'payment_method',   label: 'Paiement',      field: 'payment_method', defaultVisible: false },
    { id: 'status',           label: 'Statut',        field: 'status',        type: 'single_select', options: ['Brouillon','Soumis','Approuvé','Refusé','Remboursé','Reçue','Approuvée','Payée partiellement','Payée','En retard','Annulée'] },
  ],

  shipments: [
    { id: 'order_number',    label: '# Commande',   field: 'order_number' },
    { id: 'company_name',    label: 'Entreprise',   field: 'company_name' },
    { id: 'tracking_number', label: 'N° de suivi',  field: 'tracking_number' },
    { id: 'carrier',         label: 'Transporteur', field: 'carrier' },
    { id: 'pays',            label: 'Pays',         field: 'pays' },
    { id: 'status',          label: 'Statut',       field: 'status', type: 'single_select', options: ['À envoyer', 'Envoyé'] },
    { id: 'shipped_at',      label: 'Envoyé le',    field: 'shipped_at',  type: 'date' },
    { id: 'created_at',      label: 'Créé le',      field: 'created_at',  type: 'date' },
  ],

  stock_movements: [
    { id: 'created_at',     label: 'Date',           field: 'created_at',     type: 'date' },
    { id: 'product_sku',    label: 'SKU',            field: 'product_sku' },
    { id: 'product_name',   label: 'Produit',        field: 'product_name' },
    { id: 'type',           label: 'Type',           field: 'type',           type: 'single_select', options: ['in', 'out', 'adjustment'] },
    { id: 'qty',            label: 'Quantité',       field: 'qty',            type: 'number' },
    { id: 'reason',         label: 'Raison',         field: 'reason',         type: 'single_select', options: ['Fabrication', 'Utilisation pour le reconditionnement', 'Ajustement (augmentation)', 'Ajustement (diminution)', 'Utilisation de pièces usagés', 'Prélèvement pour R&D'] },
    { id: 'unit_cost',      label: 'Coût unitaire',  field: 'unit_cost',      type: 'number' },
    { id: 'movement_value', label: 'Valeur',         field: 'movement_value', type: 'number' },
    { id: 'user_name',      label: 'Utilisateur',    field: 'user_name',      type: 'user', defaultVisible: false },
    { id: 'reference_id',   label: 'Référence',      field: 'reference_id',   defaultVisible: false },
  ],

  journal_entries: [
    { id: 'txn_date',    label: 'Date',   field: 'txn_date',    type: 'date' },
    { id: 'doc_number',  label: 'N°',     field: 'doc_number' },
    { id: 'memo',        label: 'Mémo',   field: 'memo' },
    { id: 'lines_count', label: 'Lignes', field: 'lines_count', type: 'number', groupable: false },
    { id: 'total',       label: 'Total',  field: 'total',       type: 'number', groupable: false },
    { id: 'qb',          label: 'QB',     field: 'qb_url',      sortable: false, filterable: false, groupable: false },
  ],

  users: [
    { id: 'name',   label: 'Utilisateur', field: 'name' },
    { id: 'email',  label: 'Courriel',    field: 'email' },
    { id: 'role',   label: 'Rôle',        field: 'role',   type: 'single_select', options: ['admin', 'sales', 'support', 'ops'] },
    { id: 'active', label: 'Statut',      field: 'active', type: 'boolean' },
    { id: 'reset',  label: '',            field: '',       sortable: false, filterable: false, groupable: false },
  ],

  catalog: [
    { id: 'name_fr',           label: 'Nom FR',      field: 'name_fr' },
    { id: 'name_en',           label: 'Nom EN',      field: 'name_en' },
    { id: 'unit_price_cad',    label: 'Prix CAD',    field: 'unit_price_cad', type: 'number' },
    { id: 'price_usd',         label: 'Prix USD',    field: 'price_usd',      type: 'number' },
    { id: 'monthly_price_cad', label: 'Mensuel CAD', field: 'monthly_price_cad', type: 'number' },
    { id: 'monthly_price_usd', label: 'Mensuel USD', field: 'monthly_price_usd', type: 'number' },
    { id: 'active',            label: 'Actif',       field: 'active',         type: 'boolean', defaultVisible: false },
  ],

  soumissions: [
    { id: 'title',           label: 'Titre',       field: 'title' },
    { id: 'company_name',    label: 'Entreprise',  field: 'company_name' },
    { id: 'contact_name',    label: 'Contact',     field: 'contact_name', defaultVisible: false },
    { id: 'status',          label: 'Statut',      field: 'status', type: 'single_select', options: ['Brouillon', 'Envoyée', 'Acceptée', 'Refusée', 'Expirée'] },
    { id: 'language',        label: 'Langue',      field: 'language', type: 'single_select', options: ['French', 'English'], defaultVisible: false },
    { id: 'currency',        label: 'Devise',      field: 'currency', type: 'single_select', options: ['CAD', 'USD'], defaultVisible: false },
    { id: 'created_at',      label: 'Créée le',    field: 'created_at', type: 'date' },
    { id: 'expiration_date', label: 'Expiration',  field: 'expiration_date', type: 'date' },
    { id: 'pdf',             label: 'PDF',         field: 'generated_pdf_path', sortable: false, filterable: false, groupable: false },
  ],

  automations: [
    { id: 'name',            label: 'Nom',         field: 'name' },
    { id: 'trigger_type',    label: 'Trigger',     field: 'trigger_type', type: 'single_select', options: ['record_created', 'record_updated', 'field_changed', 'field_rule', 'schedule', 'manual', 'system'] },
    { id: 'active',          label: 'Statut',      field: 'active', type: 'boolean' },
    { id: 'last_run_at',     label: 'Dernier run', field: 'last_run_at', type: 'date' },
    { id: 'runs_30d',        label: 'Runs (30j)',  field: 'runs_30d', type: 'number' },
    { id: 'system',          label: 'Système',     field: 'system', type: 'boolean', defaultVisible: false },
    { id: 'description',     label: 'Description', field: 'description', defaultVisible: false },
  ],

  stripe_payouts: [
    { id: 'arrival_date',  label: 'Date de dépôt',  field: 'arrival_date', type: 'date' },
    { id: 'stripe_id',     label: 'Stripe ID',      field: 'stripe_id',    defaultVisible: false },
    { id: 'amount',        label: 'Montant',        field: 'amount',       type: 'number' },
    { id: 'currency',      label: 'Devise',         field: 'currency',     type: 'single_select', options: ['CAD', 'USD'] },
    { id: 'status',        label: 'Statut',         field: 'status',       type: 'single_select', options: ['paid', 'pending', 'in_transit', 'canceled', 'failed'] },
    { id: 'method',        label: 'Méthode',        field: 'method',       type: 'single_select', options: ['standard', 'instant'], defaultVisible: false },
    { id: 'type',          label: 'Type',           field: 'type',         defaultVisible: false },
    { id: 'bank',          label: 'Banque',         field: 'bank_name' },
    { id: 'qb_deposit_id', label: 'QB Deposit',     field: 'qb_deposit_id' },
    { id: 'qb_pushed_at',  label: 'Envoyé à QB',    field: 'qb_pushed_at', type: 'date', defaultVisible: false },
    { id: 'description',   label: 'Description',    field: 'description',  defaultVisible: false },
    { id: 'created_date',  label: 'Créé le',        field: 'created_date', type: 'date', defaultVisible: false },
  ],
}
