const { chromium } = require('playwright-core')
;(async () => {
  const b = await chromium.launch()
  const ctx = await b.newContext({ viewport: { width: 1500, height: 1000 } })
  const p = await ctx.newPage()
  await p.goto('http://localhost:3004/erp/login', { waitUntil: 'domcontentloaded' })
  await p.fill('input[type="email"]', 'claude@orisha.io')
  await p.fill('input[type="password"]', 'saluerlessoviets')
  await p.click('button:has-text("Se connecter")')
  await p.waitForURL(u => !u.toString().includes('/login'), { timeout: 20000 })
  await p.goto('http://localhost:3004/erp/employees/191ad678-8d5a-4ffe-a9dc-4efe72f49f71', { waitUntil: 'domcontentloaded' })
  await p.waitForTimeout(4000)
  await p.mouse.move(900, 600)
  for (let i = 0; i < 12; i++) { await p.mouse.wheel(0, 800); await p.waitForTimeout(200) }
  await p.waitForTimeout(1500)
  console.log('mentions « Photo » :', await p.getByText('Photo', { exact: false }).count())
  console.log('cf-attachments :', await p.locator('[data-testid="cf-attachments"]').count())
  console.log('imgs custom-field-files :', await p.locator('img[src*="custom-field-files"]').count())
  await p.screenshot({ path: '/tmp/employee-photo2.png' })
  await b.close()
})()
